defmodule AshDemo.Repo.Migrations.AddPostBody do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :body, :text, null: false
    end
  end

  def down do
    alter table(:posts) do
      remove :body
    end
  end
end
