defmodule AshDemo.Repo.Migrations.AddPostReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:comments, "comments_post_id_fkey")

    alter table(:comments) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "comments_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute("ALTER TABLE comments alter CONSTRAINT comments_post_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:comments, "comments_post_id_fkey")

    alter table(:comments) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "comments_post_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
