defmodule AshDemo.Repo.Migrations.RenameCommentsBody do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:comments), :body, to: :text

    alter table(:comments) do
      modify :text, :text
    end
  end

  def down do
    alter table(:comments) do
      modify :body, :text
    end

    rename table(:comments), :text, to: :body
  end
end
